# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 753a829916de505a50258397036a99d4395c11e224c2f6ca0a5eed2c528c5728b792f820ce2267536e45f92a5c1b260c502b23980a37e4465a8b319a1ba48e23

test:
  secret_key_base: a5bd2e177778da78edfa73cc9ba496979616ffd2eb04f42dcb9329cfa5d5f24d302f0809f807b2945635a085756c178814e69edae455f3f8543fd40bcc4f1ca5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
